name: LuaDec Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      createRelease:
        description: 'Create a new GitHub Release?'
        required: true
        default: 'false'
      versionName:
        description: 'version name'
        required: true
        default: 'v0.0.1'

jobs:
  try_create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.try_create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.createRelease == 'true'
        id: try_create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENFORCI }}
        with:
          tag_name: ${{ github.event.inputs.versionName }}
          release_name: LuaDec Release ${{ github.event.inputs.versionName }}
          body: LuaDec Release Description
          draft: false
          prerelease: false

  build:
    needs: try_create_release
    runs-on: windows-latest
    strategy:
      matrix:
        lua_version: ['5.1', '5.2', '5.3']
    steps:

      - name: Install MSYS2 with MinGW 64-bit
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-make

      - uses: actions/checkout@v2

      - name: Checkout submodule and build Lua
        run: |
          git submodule update --init lua-${{ matrix.lua_version }}
          cd lua-${{ matrix.lua_version }}
          mingw32-make mingw

      - name: Build luadec
        run: |
          cd luadec
          mingw32-make LUAVER=${{ matrix.lua_version }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: luadec-Lua${{ matrix.lua_version }}
          path: luadec/luadec.exe

      - name: Compress Artifacts
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.createRelease == 'true'
        run: |
          Compress-Archive -Path luadec/luadec.exe -DestinationPath luadec-Lua${{ matrix.lua_version }}_${{ github.event.inputs.versionName }}_windows_x86_64.zip
        shell: powershell

      - name: Upload Release Asset
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.createRelease == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENFORCI }}
        with:
          upload_url: ${{ needs.try_create_release.outputs.upload_url }}
          asset_path: ./luadec-Lua${{ matrix.lua_version }}_${{ github.event.inputs.versionName }}_windows_x86_64.zip
          asset_name: luadec-Lua${{ matrix.lua_version }}_${{ github.event.inputs.versionName }}_windows_x86_64.zip
          asset_content_type: application/zip