name: LuaDec Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        lua_version: ['5.1', '5.2', '5.3']
    steps:

      - name: Install MSYS2 with MinGW 64-bit
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-make

      - uses: actions/checkout@v2

      - name: Checkout submodule and build Lua
        run: |
          git submodule update --init lua-${{ matrix.lua_version }}
          cd lua-${{ matrix.lua_version }}
          mingw32-make mingw

      - name: Build luadec
        run: |
          cd luadec
          mingw32-make LUAVER=${{ matrix.lua_version }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: luadec-Lua${{ matrix.lua_version }}
          path: luadec/luadec.exe